# Transformers
Transformers are a type of deep learning model that have revolutionized the field of natural language processing (NLP) and have also been applied to other domains such as computer vision and speech recognition. They were introduced in the paper "Attention is All You Need" by Vaswani et al. in 2017.

## Transformer Architecture

The transformer architecture is based on the concept of self-attention, which allows the model to weigh the importance of different words in a sentence when making predictions. The main components of a transformer model include:

1. **Encoder**: The encoder processes the input sequence and generates a representation of it. It consists of multiple layers, each containing a self-attention mechanism and a feed-forward neural network.
2. **Decoder**: The decoder generates the output sequence based on the encoder's representation. It also consists of multiple layers, each containing a self-attention mechanism, a feed-forward neural network, and an additional attention mechanism that attends to the encoder's output.
3. **Attention Mechanism**: The attention mechanism allows the model to focus on different parts of the input sequence when generating the output. It computes a weighted sum of the input representations, where the weights are determined by the relevance of each input token to the current output token being generated.

4. **Positional Encoding**: Since transformers do not have a built-in notion of word order, positional encoding is added to the input embeddings to provide information about the position of each token in the sequence.
5. **Multi-Head Attention**: This allows the model to attend to different parts of the input sequence simultaneously, capturing various aspects of the input data.

### Transformer Data Flow Diagram

**Encoder:**
1. **Input Text**  
    ↓  
2. **Tokenization**  
    ↓  
3. **Token Encoding**  
    ↓  
4. **Token Embedding**  
    ↓  
5. **Encoder Stack (Multiple Layers with Self-Attention & Feed-Forward)**  
    ↓  
6. **Hidden States (Contextual Representations)**

---

**Decoder:**
1. **Previous Output Tokens**  
    ↓  
2. **Token Encoding**  
    ↓  
3. **Token Embedding**  
    ↓  
4. **Decoder Stack (Multiple Layers with Self-Attention, Encoder-Decoder Attention & Feed-Forward)**  
    ↓  
5. **Output Tokens**

### Somethings to know about:
- Tokenized text: The input text is tokenized into smaller units (tokens) that can be processed by the model. This can be done using various tokenization techniques, such as word-level, subword-level, or character-level tokenization.
- Token Encodings: Each token is assigned a unique integer ID based on a predefined vocabulary. This process is known as token encoding, and it allows the model to work with numerical data instead of raw text.
- Token Embeddings: Each token is converted into a dense vector representation (embedding) that captures its semantic meaning. These embeddings are learned during the training process and can be fine-tuned for specific tasks.
- Encode Stack: The encoder consists of multiple layers that process the input embeddings and generate a contextual representation of the input sequence. Each layer includes a self-attention mechanism and a feed-forward neural network.

## Text Classification

In [3]:
# !pip install transformers datasets umap-learn

In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

In [5]:
ds = load_dataset("dair-ai/emotion")
ds.set_format("pandas")

In [6]:
cls = ds['train'].features['label'].names
cls

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

0 -> sadness
1 -> joy
2 -> love
3 -> anger
4 -> fear
5 -> surprise

In [7]:
df = ds["train"][:]
df.sample(10)

                                                    text  label
2425   i feel like i ve gone a bit dull and they all ...      0
5749   i remember feeling as innocent as she looked t...      1
8061            i feel devastated disgusted and betrayed      0
11835                im just feeling very delicate today      2
3093                             i feel as dirty as fuck      0
9921   i often feel like the jaded older sister while...      0
15888  i feel respected when for months you only tell...      1
6370   i just feel like lex has convinced you that yo...      1
3021   i went to registration passed an uneventful fi...      1
142    i still feel sleep deprived she is almost slee...      0

In [8]:
df['label_name'] = df['label'].apply(lambda x: cls[x])
df.sample(10)

                                                    text  label label_name
5216   im feeling really stressed today about the sta...      0    sadness
15412  i close my eyes as you hold me close my body f...      1        joy
1468            i feel like i ll never be as graceful an      1        joy
1875   i feel a bit like franz liebkind in the produc...      1        joy
438    i feel like normally i would be angry because ...      3      anger
2622   i feel inadequate and i shut down and feel cro...      0    sadness
10859  i love the midcentury design and the vintage f...      1        joy
11020  i get so tired of pretending everything is gre...      0    sadness
4106   i feel like a blank canvas i have no clue what...      0    sadness
12806  i think of what dharavi means for mumbai and t...      3      anger

In [9]:
df['words_per_tweet'] = df['text'].str.split().apply(len)
df.head()

,text,label,label_name,words_per_tweet
0,i didnt feel humiliated,0,sadness,4
1,i can go from feeling so hopeless to so damned...,0,sadness,21
2,im grabbing a minute to post i feel greedy wrong,3,anger,10
3,i am ever feeling nostalgic about the fireplac...,2,love,18
4,i am feeling grouchy,3,anger,4

In [1]:
from transformers import AutoTokenizer

In [2]:
model_ckpt = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

c:\Users\aarad\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\aarad\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [13]:
encoded_text = tokenizer("Let's see if this works or not")
encoded_text

{'input_ids': [101, 2292, 1005, 1055, 2156, 2065, 2023, 2573, 2030, 2025, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

Here 1st and last token are special tokens. [CLS] is the first token and is used for classification tasks. [SEP] is the last token and is used to separate different sentences in tasks that involve multiple sentences.

Even with multiple setnences they seem to be 101 and 102 tokens. So we can use the same token for all the sentences.

In [15]:
tokenizer.convert_ids_to_tokens([101, 102])

['[CLS]', '[SEP]']

In [16]:
tokenizer.convert_ids_to_tokens(encoded_text.input_ids)

['[CLS]', 'let', "'", 's', 'see', 'if', 'this', 'works', 'or', 'not', '[SEP]']

Here sentence is not just tokenized but also normalized.

Every model is trained on a specific corpus and has a specific vocab. We can check it using tokenizer's vocabloury. Also every model has a max length of tokens it can process. We can check it using tokenizer's max_length attribute. If we try to encode a sentence that is longer than the max_length, it will be truncated to fit the max_length. We can also specify the truncation strategy using the truncation parameter in the tokenizer's encode method.

In [20]:
tokenizer.vocab_size , tokenizer.model_max_length

(30522, 512)

## Tokenization of our data

In [22]:
ds.reset_format()

ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2000
    })
})

In [23]:
def tokenize(batch): 
    
    tokenized_text = tokenizer(batch['text'], padding=True, truncation= True)

    return tokenized_text

In [26]:
tokenize(ds['train'][:5])

{'input_ids': [[101, 1045, 2134, 2102, 2514, 26608, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2064, 2175, 2013, 3110, 2061, 20625, 2000, 2061, 9636, 17772, 2074, 2013, 2108, 2105, 2619, 2040, 14977, 1998, 2003, 8300, 102], [101, 10047, 9775, 1037, 3371, 2000, 2695, 1045, 2514, 20505, 3308, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 2412, 3110, 16839, 9080, 12863, 2055, 1996, 13788, 1045, 2097, 2113, 2008, 2009, 2003, 2145, 2006, 1996, 3200, 102, 0], [101, 1045, 2572, 3110, 24665, 7140, 11714, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}

In [27]:
ds_encoded = ds.map(tokenize, batched=True, batch_size=None)

Map:   0%|          | 0/16000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

Map:   0%|          | 0/2000 [00:00<?, ? examples/s]

In [35]:
ds_encoded

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 16000
    })
    validation: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 2000
    })
})

## Model Building

In [38]:
from transformers import AutoModel 
import torch

tokenizer with return_tensors parameter set to "pt" will return the tokenized output as a PyTorch tensor. This is useful when we want to feed the tokenized input directly into a PyTorch model for training or inference. The output will be a dictionary containing the input_ids, attention_mask, and other relevant information in the form of PyTorch tensors.

without this param , the output will be a dictionary containing the input_ids, attention_mask, and other relevant information in the form of lists. This is useful when we want to inspect the tokenized output or use it for other purposes that do not require PyTorch tensors. This is similar to the output above where we have the input_ids and attention_mask as lists instead of tensors.

In [36]:
tokenizer("Hello macha", return_tensors="pt")

{'input_ids': tensor([[  101,  7592, 24532,  2050,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [39]:
model = AutoModel.from_pretrained(model_ckpt)
model

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_projector.bias    | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): DistilBertSelfAttention(
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(in_features=3072, out_features=768, bias=True)
          (activation): GELUActivation()
        )
        (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      )
    )
  )
)